# PostgreSQL Configuration for TripMate
# Versions 9.3 and up are supported.
# Ensure the pg gem is installed and properly configured.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: kavibakshi08
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development configuration
development:
  <<: *default
  database: tripmate_development

# Test configuration: Be cautious as this database can be reset or modified during tests.
test:
  <<: *default
  database: tripmate_test

# Production configuration: Uses environment variables for sensitive data.
production:
  <<: *default
  database: tripmate_production
  username: tripmate
  password: <%= ENV['TRIPMATE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
